# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blackacre.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blackacre.proto',
  package='pb',
  syntax='proto3',
  serialized_options=b'Z)github.com/medelman17/blackacre/server/pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x62lackacre.proto\x12\x02pb\"1\n!BlackacreSentenceSegmenterRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"7\n\"BlackacreSentenceSegmenterResponse\x12\x11\n\tsentences\x18\x01 \x03(\t\".\n\x1c\x42lackacreHealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1d\n\x1b\x42lackacreHealthCheckRequest2\xc0\x01\n\tBlackacre\x12_\n\x0cGetSentences\x12%.pb.BlackacreSentenceSegmenterRequest\x1a&.pb.BlackacreSentenceSegmenterResponse\"\x00\x12R\n\x0bHealthCheck\x12\x1f.pb.BlackacreHealthCheckRequest\x1a .pb.BlackacreHealthCheckResponse\"\x00\x42+Z)github.com/medelman17/blackacre/server/pbb\x06proto3'
)




_BLACKACRESENTENCESEGMENTERREQUEST = _descriptor.Descriptor(
  name='BlackacreSentenceSegmenterRequest',
  full_name='pb.BlackacreSentenceSegmenterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='pb.BlackacreSentenceSegmenterRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=72,
)


_BLACKACRESENTENCESEGMENTERRESPONSE = _descriptor.Descriptor(
  name='BlackacreSentenceSegmenterResponse',
  full_name='pb.BlackacreSentenceSegmenterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentences', full_name='pb.BlackacreSentenceSegmenterResponse.sentences', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=129,
)


_BLACKACREHEALTHCHECKRESPONSE = _descriptor.Descriptor(
  name='BlackacreHealthCheckResponse',
  full_name='pb.BlackacreHealthCheckResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pb.BlackacreHealthCheckResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=177,
)


_BLACKACREHEALTHCHECKREQUEST = _descriptor.Descriptor(
  name='BlackacreHealthCheckRequest',
  full_name='pb.BlackacreHealthCheckRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=208,
)

DESCRIPTOR.message_types_by_name['BlackacreSentenceSegmenterRequest'] = _BLACKACRESENTENCESEGMENTERREQUEST
DESCRIPTOR.message_types_by_name['BlackacreSentenceSegmenterResponse'] = _BLACKACRESENTENCESEGMENTERRESPONSE
DESCRIPTOR.message_types_by_name['BlackacreHealthCheckResponse'] = _BLACKACREHEALTHCHECKRESPONSE
DESCRIPTOR.message_types_by_name['BlackacreHealthCheckRequest'] = _BLACKACREHEALTHCHECKREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlackacreSentenceSegmenterRequest = _reflection.GeneratedProtocolMessageType('BlackacreSentenceSegmenterRequest', (_message.Message,), {
  'DESCRIPTOR' : _BLACKACRESENTENCESEGMENTERREQUEST,
  '__module__' : 'blackacre_pb2'
  # @@protoc_insertion_point(class_scope:pb.BlackacreSentenceSegmenterRequest)
  })
_sym_db.RegisterMessage(BlackacreSentenceSegmenterRequest)

BlackacreSentenceSegmenterResponse = _reflection.GeneratedProtocolMessageType('BlackacreSentenceSegmenterResponse', (_message.Message,), {
  'DESCRIPTOR' : _BLACKACRESENTENCESEGMENTERRESPONSE,
  '__module__' : 'blackacre_pb2'
  # @@protoc_insertion_point(class_scope:pb.BlackacreSentenceSegmenterResponse)
  })
_sym_db.RegisterMessage(BlackacreSentenceSegmenterResponse)

BlackacreHealthCheckResponse = _reflection.GeneratedProtocolMessageType('BlackacreHealthCheckResponse', (_message.Message,), {
  'DESCRIPTOR' : _BLACKACREHEALTHCHECKRESPONSE,
  '__module__' : 'blackacre_pb2'
  # @@protoc_insertion_point(class_scope:pb.BlackacreHealthCheckResponse)
  })
_sym_db.RegisterMessage(BlackacreHealthCheckResponse)

BlackacreHealthCheckRequest = _reflection.GeneratedProtocolMessageType('BlackacreHealthCheckRequest', (_message.Message,), {
  'DESCRIPTOR' : _BLACKACREHEALTHCHECKREQUEST,
  '__module__' : 'blackacre_pb2'
  # @@protoc_insertion_point(class_scope:pb.BlackacreHealthCheckRequest)
  })
_sym_db.RegisterMessage(BlackacreHealthCheckRequest)


DESCRIPTOR._options = None

_BLACKACRE = _descriptor.ServiceDescriptor(
  name='Blackacre',
  full_name='pb.Blackacre',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=211,
  serialized_end=403,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSentences',
    full_name='pb.Blackacre.GetSentences',
    index=0,
    containing_service=None,
    input_type=_BLACKACRESENTENCESEGMENTERREQUEST,
    output_type=_BLACKACRESENTENCESEGMENTERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='HealthCheck',
    full_name='pb.Blackacre.HealthCheck',
    index=1,
    containing_service=None,
    input_type=_BLACKACREHEALTHCHECKREQUEST,
    output_type=_BLACKACREHEALTHCHECKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLACKACRE)

DESCRIPTOR.services_by_name['Blackacre'] = _BLACKACRE

# @@protoc_insertion_point(module_scope)
