# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import blackacre_pb2 as blackacre__pb2


class BlackacreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSentences = channel.unary_unary(
                '/pb.Blackacre/GetSentences',
                request_serializer=blackacre__pb2.BlackacreSentenceSegmenterRequest.SerializeToString,
                response_deserializer=blackacre__pb2.BlackacreSentenceSegmenterResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/pb.Blackacre/HealthCheck',
                request_serializer=blackacre__pb2.BlackacreHealthCheckRequest.SerializeToString,
                response_deserializer=blackacre__pb2.BlackacreHealthCheckResponse.FromString,
                )


class BlackacreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSentences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlackacreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSentences': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSentences,
                    request_deserializer=blackacre__pb2.BlackacreSentenceSegmenterRequest.FromString,
                    response_serializer=blackacre__pb2.BlackacreSentenceSegmenterResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=blackacre__pb2.BlackacreHealthCheckRequest.FromString,
                    response_serializer=blackacre__pb2.BlackacreHealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.Blackacre', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Blackacre(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSentences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.Blackacre/GetSentences',
            blackacre__pb2.BlackacreSentenceSegmenterRequest.SerializeToString,
            blackacre__pb2.BlackacreSentenceSegmenterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.Blackacre/HealthCheck',
            blackacre__pb2.BlackacreHealthCheckRequest.SerializeToString,
            blackacre__pb2.BlackacreHealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
